version: "3.8"

services:
  medusa-server:
    build: .
    container_name: medusa-server
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "9000:9000"
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      JWT_SECRET: ${JWT_SECRET}
      COOKIE_SECRET: ${COOKIE_SECRET}
      STORE_CORS: ${STORE_CORS}
      ADMIN_CORS: ${ADMIN_CORS}
      AUTH_CORS: ${AUTH_CORS}
      MEDUSA_ADMIN_ONBOARDING_TYPE: ${MEDUSA_ADMIN_ONBOARDING_TYPE}
      MEDUSA_ADMIN_ONBOARDING_NEXTJS_DIRECTORY: ${MEDUSA_ADMIN_ONBOARDING_NEXTJS_DIRECTORY}
      POSTGRES_URL: ${POSTGRES_URL}
      DB_NAME: ${DB_NAME}
      STRIPE_API_KEY: ${STRIPE_API_KEY}

    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"
